### ISSUE TITLE
Milestone1 Task Tracker

### ISSUE THREAD

**Issue by lyiris22** [UBC-MDS/554_Survey#3]
- [x] Add a collaboration strategy

- [x] Add a code of conduct

- [x] Decide the topic and questions

- [x] Add the proposal
